[window]
padding = { x = 12, y = 12 }
dynamic_title = true
opacity = 0.85 # Arkası hafif görünen şık hacker teması

[font]
size = 11.0

[font.normal]
family = "Monospace"
style = "Regular"

[colors.primary]
background = "#0d1117" # PLP Gece Siyahı
foreground = "#c9d1d9"

# Terminal ilk açıldığında az önce yaptığımız yeşil PLP logosunu basar
[terminal.shell]
program = "/bin/bash"
args = ["--rcfile", "~/.bashrc", "-i", "-c", "fastfetch --config ./fastfetch.jsonc; exec /bin/bash"]
